Feature 'rating events' release. Part III
yrMajesty/java-explore-with-me pull request #7
Opened 2023-08-05 19:55 UTC by yrMajesty

2023-08-06 09:43 UTC, TomattmanYandex requested changes
Привет, пара коментариев в коде.
По поводу рейтинга, мне кажется все же лучше убрать поле рейтинг из ивента и высчитывать его при получении, либо сделать тригер в базе, который будет оновлять рейтинг при каждом обновлении эстимейшенов

2023-08-06 09:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mainservice/controller/user/EventUserController.java
> +    public ResponseEntity<Object> rateEvent(@PathVariable(name = "userId") @Positive Long userId,
так как не только в одном месте возвращается объект который содержит в себе только сообщение, лучше сделать DTO которое будет содержать одно поле,
Так ответ будет стандартизирован, и не возникнет искушения добавить неожиданно новые поля в ответ

2023-08-06 09:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mainservice/entity/Event.java
> +    private Double rating = 0.0;
это высчитваемое поле, либо надо хорошо понимать транзакции и ими оборачивать весь процесс оценки, либо убирать поле и высчитывать рейтинг при получении ивента

2023-08-06 09:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mainservice/service/EstimationService.java
> +//        if (event.getEventDate().isAfter(LocalDateTime.now())) {
закомментированный код не допускается

2023-08-06 11:36 UTC, yrMajesty commented on main-service/src/main/java/ru/practicum/mainservice/service/EstimationService.java
> +//        if (event.getEventDate().isAfter(LocalDateTime.now())) {
Это я хотел сделать чтобы оценивать можно было только события, которые уже состоялись. Но тесты тогда невозможно написать. Ведь там при создании дата до начала должна быть либо 1ч либо 2ч. Как сделать? Была мысль сделать один метод админу чтобы мог без ограничения обновлять дату события. Ну чисто для тестирования такой логики. Или не очень? Лучше убрать такое?

2023-08-06 11:38 UTC, yrMajesty commented on main-service/src/main/java/ru/practicum/mainservice/entity/Event.java
> +    private Double rating = 0.0;
А что с ним не так, не пойму? Ну обновляется же это поле если кто-то ставит рейтинг или удаляет его. Как триггер сделать, о котором ты говоришь?-_-

2023-08-06 11:39 UTC, yrMajesty commented on main-service/src/main/java/ru/practicum/mainservice/controller/user/EventUserController.java
> +    public ResponseEntity<Object> rateEvent(@PathVariable(name = "userId") @Positive Long userId,
ок. про это понял

2023-08-07 07:26 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mainservice/entity/Event.java
> +    private Double rating = 0.0;
представь ситуацию, есть ивент с одной оценкой допустим 5 (из пяти)
сразу два пользователя ставят ему оценку, но один ставит 1 а второй 5 одновременно выполняется метод на добавление новой оценки и высчитывание рейтинга, оба сразу получили все существующие оценки и у обоих лист из одного элемента 
каждый добавил свою оценку, но при этом не получил список заново, и теперь у каждого список из двух оценок (5 и 1) (5 и 5)  какой рейтинг выставится в сам ивент (зависит от того кто сохранит последним)
а теперь сами транзакции, в зависимости от настроек, они кинут ошибку в какой то момент,  и тогда может получиться, что что то вообще не сохранится

а триггеры, погугли триггеры в postgres

2023-08-07 07:28 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mainservice/service/EstimationService.java
> +//        if (event.getEventDate().isAfter(LocalDateTime.now())) {
не понимаю проблему, создаешь объект и закидываешь ему в поле значение завершения уже прошедшее время, или в базе изменяешь, а через запуск программы мы не тестируем,

2023-08-07 13:14 UTC, TomattmanYandex requested changes
У тебя левые файлы появились в корне, проверь

2023-08-08 10:39 UTC, TomattmanYandex approved these changes
По сути изменения не сильны после предыдущего ревью, рейтинг все равно хранится в базе в двух местах, но ладно, сойдет

2023-08-08 11:08 UTC, yrMajesty commented
Блин, из схемы бд забыл удалить рейтинг. Из entity 'event' удалил, а из схемы нет(

2023-08-22 13:08 UTC, merged